// src/lib/scrabbleDefinitions.js - Curated Tournament Scrabble Definitions
// Instant 0ms synchronous lookups for all two-letter words (TWL06 & CSW) and key tournament short plays.

export const SCRABBLE_DEFINITIONS = {
  // --- All 128 Two-Letter Words (TWL06 + CSW21) ---
  aa: "Rough, cindery basaltic lava",
  ab: "An abdominal muscle",
  ad: "An advertisement",
  ae: "One (Scottish)",
  ag: "Agriculture",
  ah: "Expressing delight, relief, or surprise",
  ai: "A three-toed sloth",
  al: "An East Indian tree (Morinda citrifolia)",
  am: "Present tense first person singular of be",
  an: "Indefinite article before a vowel sound",
  ar: "The letter R",
  as: "To the same degree",
  at: "Expressing location or arrival",
  aw: "Expressing protest, disgust, or sympathy",
  ax: "A cutting tool with a bladed head; to chop",
  ay: "An affirmative vote; aye",
  ba: "In ancient Egypt, the eternal soul of a person",
  be: "To exist or have a state of being",
  bi: "A bisexual person",
  bo: "A friend or fellow (slang)",
  by: "Near; through the agency of",
  ch: "Dialect variant of I (Scottish/English dial.)",
  da: "A father (slang/dialect)",
  de: "Of, from (used in names)",
  di: "Plural of deus (gods)",
  do: "To perform or execute; first tone of diatonic scale",
  ea: "A river (dialect)",
  ed: "Education (slang)",
  ee: "An eye (Scottish)",
  ef: "The letter F",
  eh: "Expressing inquiry or seeking confirmation",
  el: "An elevated railroad or train",
  em: "A printer’s unit of measurement equal to font size",
  en: "A printer’s unit of measurement equal to half an em",
  er: "Expressing hesitation or doubt",
  es: "The letter S (plural: esses)",
  et: "Past tense of eat (dialect)",
  ew: "Expressing disgust",
  ex: "The letter X; a former partner",
  ey: "An island (archaic)",
  fa: "The fourth tone of the diatonic scale",
  fe: "A Hebrew letter (pe)",
  gi: "A martial arts uniform",
  go: "To move or proceed; a Japanese board game",
  gu: "A simple violin of the Shetland Islands",
  ha: "An exclamation of triumph, surprise, or laughter",
  he: "A male person or animal",
  hi: "A friendly greeting",
  hm: "Expressing thoughtful consideration or hesitation",
  ho: "An exclamation calling attention or expressing surprise",
  id: "Part of the psyche in psychoanalysis",
  if: "Supposing that; on condition that",
  in: "Located within; having influence",
  io: "A cry of joy or triumph; a hawk",
  is: "Present tense third person singular of be",
  it: "The thing previously mentioned",
  ja: "Yes (German/Afrikaans/slang)",
  jo: "A sweetheart or darling (Scottish)",
  ka: "In ancient Egypt, the spiritual double or soul",
  ki: "The circulating life energy (variant of qi)",
  ko: "A Maori digging stick",
  ky: "Cows; kine (Scottish)",
  la: "The sixth tone of the diatonic scale",
  li: "A traditional Chinese unit of distance",
  lo: "Look! See! (archaic exclamation)",
  ma: "Mother (informal)",
  me: "Objective case of the pronoun I",
  mi: "The third tone of the diatonic scale",
  mm: "Expressing agreement, contentment, or savoring",
  mo: "A moment (slang)",
  mu: "The 12th letter of the Greek alphabet",
  my: "Belonging to me",
  na: "No; not (Scottish/dialect)",
  ne: "Born with the name of; nor (archaic)",
  no: "A negative response; not any",
  nu: "The 13th letter of the Greek alphabet",
  ny: "To approach or draw near (archaic)",
  ob: "An objection",
  od: "A hypothetical mystical universal force",
  oe: "A violent whirlwind off the Faroe Islands",
  of: "Belonging to; indicating origin",
  oh: "Expressing surprise, joy, or apprehension",
  oi: "A call to attract attention (British/slang)",
  oj: "Orange juice (slang)",
  ok: "All right; acceptable; approve",
  om: "A sacred mantra in Hinduism and Buddhism",
  on: "Positioned above and supported by",
  oo: "Wool (Scottish)",
  op: "An operation (slang); work of art",
  or: "Conjunction indicating an alternative; gold in heraldry",
  os: "A bone; an opening or orifice; an esker",
  ou: "A bloke or fellow (South African)",
  ow: "Expressing sudden pain",
  ox: "A domesticated bovine mammal",
  oy: "Expressing dismay, exasperation, or grief",
  pa: "Father (informal)",
  pe: "A Hebrew letter",
  pi: "The 16th letter of the Greek alphabet (ratio ~3.14159)",
  po: "A chamber pot (slang)",
  qi: "The circulating life force in Chinese philosophy",
  re: "The second tone of the diatonic scale; regarding",
  sh: "Urging silence; hush",
  si: "The seventh tone of the diatonic scale; ti",
  so: "To that extent; fifth tone of the diatonic scale",
  st: "Expressing impatience or calling attention; hush",
  ta: "Thank you (British/informal)",
  te: "The seventh tone of the diatonic scale; ti",
  ti: "The seventh tone of the diatonic scale",
  to: "In the direction of",
  ug: "To feel dread, disgust, or horror (Scottish/dialect)",
  uh: "Expressing hesitation or uncertainty",
  um: "Expressing hesitation, doubt, or thinking",
  un: "One (dialect/informal)",
  up: "Toward a higher place or position",
  ur: "Expressing hesitation (variant of er); primitive",
  us: "Objective case of we",
  ut: "The first note of the Guidonian hexachord",
  we: "Nominative plural of I",
  wo: "Woe; grief (archaic)",
  xi: "The 14th letter of the Greek alphabet",
  xu: "A monetary unit of Vietnam (one-hundredth of a dong)",
  ya: "You (informal); affirmative",
  ye: "You (archaic plural/dialect)",
  yo: "Calling attention or expressing greeting",
  yu: "Precious jade (Chinese)",
  za: "A pizza (slang)",
  ze: "Gender-neutral pronoun",
  zo: "A Tibetan crossbreed between a yak and domestic cow",

  // --- High-Frequency Scrabble Short Plays & Power Words ---
  qat: "An Arabian shrub whose leaves are chewed as a stimulant",
  suq: "A marketplace in an Arab city (souk)",
  qis: "(pl.) Plural of qi (circulating life forces)",
  qid: "A four-times-a-day medical dosage; or variant of quid",
  zas: "(pl.) Plural of za (pizzas)",
  zek: "A prisoner in a Soviet labor camp (Gulag)",
  zax: "A hatchet-like tool used for cutting and trimming roof slates",
  zep: "A large submarine sandwich (zeppelin)",
  zoa: "(pl.) Plural of zoon (individual animals or zooids)",
  zuz: "An ancient Hebrew silver coin",
  cwm: "A steep-sided hollow at the head of a valley (cirque)",
  crwth: "An ancient Celtic bowed string instrument",
  vau: "The sixth letter of the Hebrew alphabet (vav)",
  vox: "Voice; sound (Latin)",
  vav: "The sixth letter of the Hebrew alphabet",
  xis: "(pl.) Plural of xi (14th letters of Greek alphabet)",
  xus: "(pl.) Plural of xu (Vietnamese currency units)",
  jow: "To toll or ring a bell (Scottish)",
  jee: "To turn or move to one side (gee)",
  jud: "A mass of coal ready to be brought down in mining",
  jeu: "A game; play of wit (French)",
  baa: "The cry of a sheep",
  biz: "Business (slang)",
  bub: "A young boy or fellow",
  caz: "Casual (slang)",
  coz: "Cousin (archaic/informal)",
  dey: "A former governor of Algiers",
  dit: "A dot in Morse code; a short poem or song",
  dos: "(pl.) Plural of do (actions; first diatonic notes)",
  dup: "To open (archaic)",
  fiz: "A hissing sound (fizz)",
  gab: "Chatter; idle or excessive talk",
  gam: "A social visit between whalers; a school of whales",
  gen: "General information (British slang)",
  gio: "A narrow coastal inlet bounded by cliffs (Scottish)",
  gju: "A traditional Shetland two-stringed violin",
  gox: "Gaseous oxygen",
  gyp: "To swindle or cheat",
  haj: "The pilgrimage to Mecca (hajj)",
  hic: "Representing the sound of a hiccup",
  hox: "To hock or hamstring",
  hoi: "Exclamation used to attract attention",
  iwi: "A Maori tribe or community",
  kab: "An ancient Hebrew measure of capacity",
  kat: "Variant of qat (stimulant shrub)",
  kex: "The dry hollow stalk of umbelliferous plants",
  koi: "A decorative domesticated Japanese carp",
  kop: "A small hill or mound (South African)",
  kor: "An ancient Hebrew unit of capacity",
  kos: "A measure of distance in India (~2 miles)",
  lev: "The monetary unit of Bulgaria",
  lox: "Liquid oxygen; brine-cured smoked salmon",
  luv: "Term of endearment (love)",
  moa: "An extinct giant flightless bird of New Zealand",
  nah: "No (informal)",
  nim: "An ancient game of taking items from piles",
  nox: "Night (Latin/poetic)",
  nth: "Pertaining to an unspecified large number or degree",
  obi: "A broad sash worn with a kimono; West African sorcery",
  ora: "(pl.) Plural of os (mouths, openings, or bones)",
  ort: "A scrap or morsel of leftover food",
  oud: "A pear-shaped Middle Eastern stringed instrument",
  oxy: "Containing oxygen; short for oxycodone",
  pac: "A moccasin-style boot or shoe",
  pah: "Exclamation of disgust or disdain",
  pam: "The jack of clubs in five-card loo",
  ped: "A natural soil aggregate",
  peh: "Variant of pe (Hebrew letter)",
  pho: "A traditional Vietnamese beef noodle soup",
  pht: "Exclamation of annoyance or dismissal",
  poh: "Exclamation of contempt (pooh)",
  poi: "A traditional fermented Hawaiian taro paste",
  pol: "A politician (informal)",
  pro: "In favor of; a professional",
  pud: "A sweet pudding or dessert (British slang)",
  pug: "A breed of toy dog; to temper clay with water",
  pyx: "A sacred vessel for the consecrated Eucharist",
  rai: "A genre of Algerian folk and pop music",
  raj: "Rule or sovereignty, esp. the British Raj in India",
  rax: "To stretch out after sleep (Scottish)",
  ria: "A long narrow inlet formed by a submerged river valley",
  roc: "A mythical bird of enormous size and strength",
  rya: "A traditional Scandinavian knotted-pile wool rug",
  sab: "To sob (Scottish/dialect)",
  saj: "A convex Middle Eastern metal baking griddle",
  ska: "A Jamaican music style originating in the late 1950s",
  som: "The basic monetary unit of Kyrgyzstan",
  sop: "Bread dipped in liquid; a placatory concession",
  sri: "An Indian title of respect prefixed to names",
  taj: "A tall conical cap or crown worn in Muslim countries",
  tam: "A flat round wool cap with a pompom (tam-o'-shanter)",
  tao: "The underlying fundamental order of nature in Taoism",
  tav: "The 22nd and last letter of the Hebrew alphabet",
  taw: "A fancy marble used as a shooter in marbles",
  teg: "A two-year-old sheep",
  tel: "An ancient mound formed by the debris of successive settlements",
  tet: "The Vietnamese Lunar New Year festival",
  tew: "To work hard, toil, or hustle (dialect)",
  tix: "Tickets (slang)",
  tod: "A bushy mass; an old British weight (~28 lbs); a fox",
  tog: "To dress up; garments or clothing",
  tut: "Exclamation expressing impatience or mild reproof",
  twa: "Two (Scottish)",
  tye: "A rope or chain used in hoisting a ship's yard",
  udo: "A Japanese herb with crisp edible shoots",
  ulu: "An Inuit woman's crescent-bladed utility knife",
  ump: "An umpire (informal)",
  urd: "An Asian legume cultivated for its black seeds",
  urp: "To vomit or burp (slang)",
  uta: "A genus of small side-blotched iguanian lizards",
  ute: "A utility vehicle (Australian); a member of the Ute tribe",
  vac: "A vacuum cleaner (informal); vacation",
  var: "A unit of reactive electric power",
  vav: "The sixth letter of the Hebrew alphabet",
  vaw: "Variant spelling of vav",
  vee: "The letter V",
  veg: "Vegetables; to relax idly (slang)",
  vet: "A veterinarian; a military veteran",
  vig: "Vigorish; an illegal bookmaker's fee or interest",
  vim: "Lively vigor, energy, and robust enthusiasm",
  vin: "Wine (French)",
  vis: "Force, physical power, or efficacy (Latin)",
  vly: "A shallow swamp, bog, or marsh (dialect)",
  voe: "A narrow sea inlet or fjord in Shetland and Orkney",
  vow: "A solemn promise or pledge",
  waw: "A wave (Scottish); letter in the Arabic alphabet",
  waz: "To urinate (British slang)",
  wen: "A sebaceous skin cyst; an overcrowded metropolis",
  wha: "Who (Scottish)",
  wis: "To know, believe, or suppose (archaic)",
  wiz: "A wizard or someone extraordinarily skilled (slang)",
  woe: "Intense grief, misery, or distress",
  wok: "A round-bottomed steel cooking pan in Asian cuisine",
  wot: "To know or be aware of (archaic)",
  wow: "Exclamation of astonishment, wonder, or admiration",
  wry: "Dryly humorous, ironic, or contorted",
  wud: "Mad, insane, or furious (Scottish)",
  wye: "The letter Y; a three-way track intersection",
  wyn: "An ancient Anglo-Saxon runic letter representing /w/",
  xed: "Crossed out or marked with an X",
  yad: "A ritual pointer used when reading the Torah",
  yah: "Exclamation of disdain; or yes (slang)",
  yak: "A large long-haired wild ox of Central Asia",
  yam: "An edible starchy tuber of tropical vines",
  yap: "To bark sharply; shrill continuous chatter",
  yar: "Nimble, quick, and easily handled (nautical)",
  yaw: "To swerve temporarily off course",
  yay: "Exclamation celebrating victory, joy, or approval",
  yen: "The monetary currency of Japan; a strong yearning",
  yep: "Yes (informal)",
  yew: "An evergreen conifer with red berries and elastic wood",
  yex: "To hiccup (archaic)",
  yin: "The passive feminine principle in Chinese philosophy",
  yip: "A short, sharp bark or squeal",
  yob: "An uncouth, belligerent young man (British slang)",
  yod: "The tenth letter of the Hebrew alphabet",
  yok: "A hearty laugh or joke (slang)",
  yom: "Day (Hebrew, as in Yom Kippur)",
  yon: "Yonder; in that direction over there",
  yow: "Exclamation of sharp pain or surprise",
  yuk: "A loud hearty laugh; exclamation of disgust",
  yum: "Exclamation savoring delicious food",
  yup: "Yes (informal)",
  zag: "A sharp turn in an alternating zigzag course",
  zap: "To destroy, strike, or shock with lightning speed",
  zea: "The botanical genus comprising maize (corn)",
  zed: "The letter Z (British/Commonwealth English)",
  zee: "The letter Z (American English)",
  zen: "A Mahayana Buddhist practice emphasizing zazen meditation",
  zig: "A sharp directional turn forming part of a zigzag",
  zin: "Zinfandel red wine (informal)",
  zip: "To fasten with a zipper; brisk speed or energy; zero",
  zit: "A skin pimple (informal)",
};
